Repository googleapis/nodejs-video-intelligence, pull requests merged in 2019-05, with the labels that each got.

#224 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#223 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#225 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#228 fix: DEADLINE_EXCEEDED no longer treated as idempotent and retried
  .kokoro/test.bat
  src/v1/video_intelligence_service_client.js
  src/v1/video_intelligence_service_client_config.json
  src/v1beta1/video_intelligence_service_client_config.json
  src/v1beta2/video_intelligence_service_client_config.json
  src/v1p1beta1/video_intelligence_service_client_config.json
  src/v1p2beta1/video_intelligence_service_client_config.json
  src/v1p3beta1/streaming_video_intelligence_service_client_config.json
  src/v1p3beta1/video_intelligence_service_client_config.json
  synth.metadata
  system-test/video_intelligence_service_smoke_test.js
  test/gapic-v1.js
Labels: cla: yes

#229 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#231 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#232 build: only pipe Node 10 build results to codecov
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#234 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v1/video_intelligence_service_client.js
  src/v1/video_intelligence_service_client_config.json
  src/v1beta1/video_intelligence_service_client_config.json
  src/v1beta2/video_intelligence_service_client_config.json
  src/v1p1beta1/video_intelligence_service_client_config.json
  src/v1p2beta1/video_intelligence_service_client_config.json
  src/v1p3beta1/streaming_video_intelligence_service_client_config.json
  src/v1p3beta1/video_intelligence_service_client_config.json
  synth.metadata
  test/gapic-v1.js
Labels: cla: yes

#235 chore: release 2.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#236 fix: update min dependencies and use repo-tools to generate README
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  synth.metadata
  synth.py
Labels: cla: yes

#237 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#241 chore: release 2.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#243 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1/video_intelligence_service_client.js
  src/v1beta1/video_intelligence_service_client.js
  src/v1beta2/video_intelligence_service_client.js
  src/v1p1beta1/video_intelligence_service_client.js
  src/v1p2beta1/video_intelligence_service_client.js
  src/v1p3beta1/streaming_video_intelligence_service_client.js
  src/v1p3beta1/video_intelligence_service_client.js
  synth.metadata
Labels: cla: yes

#244 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#245 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#246 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#247 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
