Repository googleapis/nodejs-video-intelligence, pull requests merged in 2019-09, with the labels that each got.

#281 feat: segment and shot label annotations support
  protos/google/cloud/videointelligence/v1/video_intelligence.proto
  protos/protos.json
  src/service_proto_list.json
  src/v1/doc/google/cloud/videointelligence/v1/doc_video_intelligence.js
  synth.metadata
  synth.py
Labels: cla: yes, status: blocked

#288 chore: remove conformance tests from .nycrc
  .nycrc
Labels: cla: yes

#286 feat: load protos from JSON, grpc-fallback support
  README.md
  protos/protos.json
  src/browser.js
  src/v1/video_intelligence_service_client.js
  src/v1/video_intelligence_service_proto_list.json
  src/v1beta1/video_intelligence_service_client.js
  src/v1beta1/video_intelligence_service_proto_list.json
  src/v1beta2/video_intelligence_service_client.js
  src/v1beta2/video_intelligence_service_proto_list.json
  src/v1p1beta1/video_intelligence_service_client.js
  src/v1p1beta1/video_intelligence_service_proto_list.json
  src/v1p2beta1/video_intelligence_service_client.js
  src/v1p2beta1/video_intelligence_service_proto_list.json
  src/v1p3beta1/streaming_video_intelligence_service_client.js
  src/v1p3beta1/streaming_video_intelligence_service_proto_list.json
  src/v1p3beta1/video_intelligence_service_client.js
  src/v1p3beta1/video_intelligence_service_proto_list.json
  synth.metadata
  test/gapic-v1.js
  test/gapic-v1beta1.js
  test/gapic-v1beta2.js
  test/gapic-v1p1beta1.js
  test/gapic-v1p2beta1.js
  test/gapic-v1p3beta1.js
  webpack.config.js
Labels: cla: yes

#285 chore: release 2.3.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#296 chore: update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#293 feat: .d.ts for protos
  .eslintignore
  .github/release-please.yml
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  protos/protos.d.ts
  protos/protos.js
  samples/system-test/analyze.test.js
  samples/system-test/analyze.v1p2beta1.test.js
  synth.metadata
Labels: cla: yes
