Repository googleapis/nodejs-video-intelligence, pull requests merged in 2019-03, with the labels that each got.

#203 docs: update comments on protos
  protos/google/cloud/videointelligence/v1/video_intelligence.proto
  protos/google/cloud/videointelligence/v1beta1/video_intelligence.proto
  protos/google/cloud/videointelligence/v1beta2/video_intelligence.proto
  protos/google/cloud/videointelligence/v1p1beta1/video_intelligence.proto
  protos/google/cloud/videointelligence/v1p2beta1/video_intelligence.proto
  protos/google/cloud/videointelligence/v1p3beta1/video_intelligence.proto
  src/v1/doc/google/cloud/videointelligence/v1/doc_video_intelligence.js
  src/v1/video_intelligence_service_client.js
  src/v1beta1/doc/google/cloud/videointelligence/v1beta1/doc_video_intelligence.js
  src/v1beta1/video_intelligence_service_client.js
  src/v1beta2/doc/google/cloud/videointelligence/v1beta2/doc_video_intelligence.js
  src/v1beta2/video_intelligence_service_client.js
  src/v1p1beta1/doc/google/cloud/videointelligence/v1p1beta1/doc_video_intelligence.js
  src/v1p1beta1/video_intelligence_service_client.js
  src/v1p2beta1/doc/google/cloud/videointelligence/v1p2beta1/doc_video_intelligence.js
  src/v1p2beta1/video_intelligence_service_client.js
  src/v1p3beta1/doc/google/cloud/videointelligence/v1p3beta1/doc_video_intelligence.js
  src/v1p3beta1/video_intelligence_service_client.js
  synth.metadata
Labels: cla: yes

#202 Object tracking and Text detection GA samples
  samples/analyze.js
  samples/package.json
  samples/system-test/analyze.test.js
Labels: cla: yes, needs work

#204 build: update release configuration
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#205 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#206 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#208 docs: update jsdoc samples and json import paths
  src/v1/video_intelligence_service_client.js
  src/v1beta1/video_intelligence_service_client.js
  src/v1beta2/video_intelligence_service_client.js
  src/v1p1beta1/video_intelligence_service_client.js
  src/v1p2beta1/video_intelligence_service_client.js
  src/v1p3beta1/streaming_video_intelligence_service_client.js
  src/v1p3beta1/video_intelligence_service_client.js
  synth.metadata
Labels: cla: yes

#209 docs: use backticks for JS values
  src/v1/doc/google/longrunning/doc_operations.js
  src/v1beta1/doc/google/longrunning/doc_operations.js
  src/v1beta2/doc/google/longrunning/doc_operations.js
  src/v1p1beta1/doc/google/longrunning/doc_operations.js
  src/v1p2beta1/doc/google/longrunning/doc_operations.js
  src/v1p3beta1/doc/google/longrunning/doc_operations.js
  synth.metadata
Labels: cla: yes

#211 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: cla: yes

#212 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes

#210 Streaming beta samples
  samples/analyze-streaming-annotation-to-storage.js
  samples/analyze-streaming-labels.js
  samples/analyze-streaming-object.js
  samples/analyze-streaming-safe-search.js
  samples/analyze-streaming-shot-change.js
  samples/system-test/analyze-streaming-annotation-to-storage.test.js
  samples/system-test/analyze-streaming-labels.test.js
  samples/system-test/analyze-streaming-object.test.js
  samples/system-test/analyze-streaming-safe-search.test.js
  samples/system-test/analyze-streaming-shot-change.test.js
Labels: :rotating_light:, cla: yes
