Repository googleapis/nodejs-video-intelligence, pull requests merged in 2020-10, with the labels that each got.

#478 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#486 chore: fixes the flaky tests
  package.json
  samples/system-test/analyze-streaming-shot-change.test.js
  samples/system-test/analyze_face_detection.test.js
  samples/system-test/analyze_face_detection_gcs.test.js
Labels: automerge, cla: yes

#487 chore: added retry logic for flaky tests
  samples/system-test/analyze-streaming-automl-classification.test.js
  samples/system-test/analyze-streaming-labels.test.js
Labels: cla: yes

#488 build: update to the latest build config
  .github/workflows/ci.yaml
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: cla: yes, context: full
