Repository googleapis/nodejs-video-intelligence, pull requests merged in 2020-06, with the labels that each got.

#436 fix!: synth.py clean up for multiple version
  src/index.ts
  synth.metadata
  synth.py
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
Labels: cla: yes

#440 chore: update protos.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#445 build(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v1/video_intelligence_service_client.ts
  src/v1beta2/video_intelligence_service_client.ts
  src/v1p1beta1/video_intelligence_service_client.ts
  src/v1p2beta1/video_intelligence_service_client.ts
  src/v1p3beta1/streaming_video_intelligence_service_client.ts
  src/v1p3beta1/video_intelligence_service_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#447 fix: handle fallback option properly
  .kokoro/populate-secrets.sh
  src/v1/video_intelligence_service_client.ts
  src/v1beta2/video_intelligence_service_client.ts
  src/v1p1beta1/video_intelligence_service_client.ts
  src/v1p2beta1/video_intelligence_service_client.ts
  src/v1p3beta1/streaming_video_intelligence_service_client.ts
  src/v1p3beta1/video_intelligence_service_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#449 fix: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#450 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
