Repository googleapis/nodejs-video-intelligence, pull requests merged in 2020-07, with the labels that each got.

#452 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#453 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#456 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#458 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#459 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: automerge, cla: yes, context: none

#460 build: missing parenthesis in publish script, delete Node 8 tests, add config for cloud-rad for nodejs
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#461 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#462 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#463 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#465 docs: link to CHANGELOG in README
  .kokoro/release/docs-devsite.cfg
  README.md
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: partial
