Repository googleapis/nodejs-video-intelligence, pull requests merged in 2020-11, with the labels that each got.

#490 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full

#491 samples: refactored speech transcribe sample to meet same standards a…
  samples/analyze.js
Labels: api: videointelligence, cla: yes

#493 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/video_intelligence_service_client.ts
  src/v1beta2/video_intelligence_service_client.ts
  src/v1p1beta1/video_intelligence_service_client.ts
  src/v1p2beta1/video_intelligence_service_client.ts
  src/v1p3beta1/streaming_video_intelligence_service_client.ts
  src/v1p3beta1/video_intelligence_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: videointelligence, automerge, cla: yes

#501 fix(browser): check for fetch on window
  package.json
  protos/protos.json
  src/v1/video_intelligence_service_client.ts
  src/v1beta2/video_intelligence_service_client.ts
  src/v1p1beta1/video_intelligence_service_client.ts
  src/v1p2beta1/video_intelligence_service_client.ts
  src/v1p3beta1/streaming_video_intelligence_service_client.ts
  src/v1p3beta1/video_intelligence_service_client.ts
  synth.metadata
  test/gapic_video_intelligence_service_v1.ts
  test/gapic_video_intelligence_service_v1beta2.ts
  test/gapic_video_intelligence_service_v1p1beta1.ts
  test/gapic_video_intelligence_service_v1p2beta1.ts
  test/gapic_video_intelligence_service_v1p3beta1.ts
Labels: api: videointelligence, cla: yes, context: none

#503 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full
