Repository googleapis/nodejs-video-intelligence, pull requests merged in 2020-05, with the labels that each got.

#435 feat: check status of long running operation by its name
  src/v1/video_intelligence_service_client.ts
  src/v1beta2/video_intelligence_service_client.ts
  src/v1p1beta1/video_intelligence_service_client.ts
  src/v1p2beta1/video_intelligence_service_client.ts
  src/v1p3beta1/video_intelligence_service_client.ts
  synth.metadata
  test/gapic_streaming_video_intelligence_service_v1p3beta1.ts
  test/gapic_video_intelligence_service_v1.ts
  test/gapic_video_intelligence_service_v1beta2.ts
  test/gapic_video_intelligence_service_v1p1beta1.ts
  test/gapic_video_intelligence_service_v1p2beta1.ts
  test/gapic_video_intelligence_service_v1p3beta1.ts
Labels: automerge, cla: yes

#438 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#439 feat(v1p3beta1): added support for streaming automl action recognition.
  protos/google/cloud/videointelligence/v1p3beta1/video_intelligence.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1p3beta1/streaming_video_intelligence_service_client.ts
  src/v1p3beta1/video_intelligence_service_client.ts
  synth.metadata
Labels: cla: yes, context: full
