Repository googleapis/nodejs-video-intelligence, pull requests merged in 2021-01, with the labels that each got.

#514 chore: increased timeout on flaky service
  samples/analyze-streaming-object.js
Labels: api: videointelligence, cla: yes

#513 docs: update dates
  .jsdoc.js
  protos/protos.d.ts
  protos/protos.js
  src/v1/index.ts
  src/v1/video_intelligence_service_client.ts
  src/v1beta2/index.ts
  src/v1beta2/video_intelligence_service_client.ts
  src/v1p1beta1/index.ts
  src/v1p1beta1/video_intelligence_service_client.ts
  src/v1p2beta1/index.ts
  src/v1p2beta1/video_intelligence_service_client.ts
  src/v1p3beta1/index.ts
  src/v1p3beta1/streaming_video_intelligence_service_client.ts
  src/v1p3beta1/video_intelligence_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_streaming_video_intelligence_service_v1p3beta1.ts
  test/gapic_video_intelligence_service_v1.ts
  test/gapic_video_intelligence_service_v1beta2.ts
  test/gapic_video_intelligence_service_v1p1beta1.ts
  test/gapic_video_intelligence_service_v1p2beta1.ts
  test/gapic_video_intelligence_service_v1p3beta1.ts
Labels: api: videointelligence, automerge, cla: yes, context: none

#515 docs: update go link
  protos/protos.json
  synth.metadata
Labels: api: videointelligence, cla: yes, context: none

#517 docs: update typo analyze.js
  samples/analyze.js
Labels: api: videointelligence, cla: yes

#519 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: videointelligence, automerge, cla: yes, context: full
