Repository googleapis/nodejs-video-intelligence, pull requests merged in 2021-05, with the labels that each got.

#544 fix(deps): require google-gax v2.12.0
  package.json
Labels: api: videointelligence, automerge, cla: yes

#547 samples: add streaming_automl_object_tracking sample
  README.md
  linkinator.config.json
  samples/README.md
  samples/analyze-streaming-automl-object-tracking.js
  samples/system-test/analyze-streaming-automl-object-tracking.test.js
Labels: api: videointelligence, cla: yes, samples, type: docs

#553 fix: remove doc config exception
  linkinator.config.json
Labels: api: videointelligence, cla: yes
